#Specify a base image lts long term 
FROM node:lts-alpine
#Start process node / api
WORKDIR '/opt/app/api_employeees'
#copy dependencies  from client to wordir
COPY './package*.json' '.'
#Install modules
RUN npm install
#Copy files
COPY '.' '.'
#construir build
RUN npm run build
#Default command
CMD ["npm","run","prod"]